name: pytorch-nst
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8  # Python 3.7 is outdated, use 3.8 for better compatibility
  - pip
  - matplotlib
  - pytorch
  - torchvision
  - numpy
  - opencv
  - scipy
  - pillow
  - tqdm
  - pip:
      - opencv-python  # Install OpenCV via pip if needed